
title: Maxime Lenne resume / CV
url: 'https://maxime-lenne.github.io/'
#baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Maxime Lenne
tagline: Entrepreneur - Full Stack Developer
taglinefr: 'Entrepreneur - DÃ©veloppeur full stack'
pic: profile.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: maxime.lenne@gmail.com
phone: +33 6 29 45 38 14
#site: #do not add http://s
medium: '@MaximeLenne'
linkedin: maximelenne
github: maxime-lenne
twitter: '@MaximeLenne'


# Tracker
analytics: UA-12707035-10
#Update all the sections by editing the files inside _includes folder.
